version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: pizzeria_container
    restart: always
    environment:
      MYSQL_DATABASE: pizzeria_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"